title: "질문"
body:
  - type: markdown
    attributes:
      value: |
        ## 🏷️ 주제 선택

  - type: dropdown
    id: category
    attributes:
      label: 토론 주제를 선택해주세요
      description: 가장 적합한 주제를 선택해주세요
      options:
        - Database
        - Infra
        - Spring
        - JPA
        - Network
        - OS
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 📝 토론 참여자 목록
        ```
        @Libienz 
        @Ho-Tea 
        @hyeon0208 
        @hoyeonyy 
        ```
        ---

  - type: input
    id: participants
    attributes:
      label: 😀 참여자
      description: 위 목록에서 토론에 참여할 분들을 복사하여 태그해주세요
      placeholder: "@username1 @username2"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### ❓ 꼬리 질문 작성

  - type: textarea
    id: additional-questions
    attributes:
      label: 💭 꼬리 질문 목록
      description: 추가로 궁금한 질문들을 작성해주세요.
      placeholder: |
        1. 첫 번째 질문
        2. 두 번째 질문
        3. 세 번째 질문
        ...
    validations:
      required: true
